### PR TITLE
Revert "Edit: updated version string"

### PR DESCRIPTION
**Pull request by magicaldave**
This reverts commit 7c21d6ddcce7a4c9b18ffd515d4d5002a387154d.

### CODE REVIEW

**Comment by HotaruBlaze** [comment]
Wouldn't it be better to change it back to 0.8.1?, as their is no 0.8.2 version right now?

**Comment by magicaldave** [comment]
> now

Ahh, it would. I simply reverted my manual edit but the version is from having actually merged in the .8.2 branch of corescripts. I can fix it!

**Comment by magicaldave** [comment]
Our corescripts is currently broken without this change, and it affects our CI, so I'm going to go ahead and merge this without review.

**Comment by HotaruBlaze** [comment]
👍 I forgot to mark this as approved

**Pull request merged**
